baseURL = "https://dakerfp.com"
title = "Daker Pinheiro"
copyright = "Ⓒ 2017 Daker Fernandes Pinheiro"

theme = "minimo"

disqusShortname = "dakerfp"
googleAnalytics = "UA-80351639-1"
Paginate = 30

preserveTaxonomyNames = true

[params]
  description = "My home page & blog"
  dateFormat = "2006, Jan 2"
  copyrightOwner = "Daker Fernandes Pinheiro"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]
  hideSocialMenu = false
  showReadTime = true
  showAuthor = true

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = "dakerfp"

[author]
  name = "Daker"

[author.social]
  facebook = "dakerfp"
  github = "http://github.com/dakerfp"
  twitter = "dakerfp"

[permalinks]
  page = "/:slug/"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
